#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 7.4j
#  in conjunction with Tcl 2version 8.6
#    Apr 10, 2022 11:36:01 AM PDT  platform: Linux

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import tip

def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol( 'WM_DELETE_WINDOW' , root.destroy)
    # Creates a toplevel widget.
    global _top43, _w43
    _top43 = root
    _w43 = tip.Toplevel1(_top43)
    # Creates a toplevel widget.
    init(_top43, _w43)
    root.mainloop()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def change(*args):
    print('tip_support.change')
    sys.stdout.flush()
    w.btn_dest_tooltip.update("New tooltip")
    # The following code works because the ToolTip class was defined
    # in the GUI module and the that code was placed there because I
    # had created tooltips in the GUI.
    import tip
    other_tip = tip.ToolTip(w.btn_quit,w.tooltip_font,"Exit Button",delay=0.5)

def quit(*args):
    print('tip_support.quit')
    for arg in args:
        print ('another arg:', arg)
    sys.stdout.flush()
    sys.exit()

if __name__ == '__main__':
    tip.start_up()





