#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5a
#  in conjunction with Tcl version 8.6
#    Jan 24, 2020 10:12:01 AM PST  platform: Linux
#    Jan 24, 2020 10:14:58 AM PST  platform: Linux

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True
    
def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top
    print("middle_support: init: root = %s" % root)

import popup
    
def invoke():
    print('middle_support.invoke')
    sys.stdout.flush()
    print("middle_support: invoke: root = %s" % root)
    popup.create_popup(root)

def quit():
    print('middle_support.quit')
    sys.stdout.flush()
    sys.exit()

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import middle
    middle.vp_start_gui()





