#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 7m
#  in conjunction with Tcl version 8.6
#    Aug 08, 2021 09:43:49 PM PDT  platform: Linux

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import cal

def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol( 'WM_DELETE_WINDOW' , root.destroy)
    # Creates a toplevel widget.
    global _top42, _w42
    _top42 = root
    _w42 = cal.Toplevel1(_top42)
    root.mainloop()

def quit(*args):
    print('cal_support.quit')
    sys.stdout.flush()
    sys.exit()

from ttkwidgets import Calendar
class Cal(Calendar):
    def __init__(self, master,):
        super().__init__(master,
                          selectforeground='white', selectbackground='red')
Custom = Cal

if __name__ == '__main__':
    cal.start_up()




