#############################################################################
# Generated by PAGE version 4.17.4
# in conjunction with Tcl version 8.6
# Sep 16, 2018 09:47:25 PM PDT  platform: Linux
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

vTcl:font:add_GUI_font font10 \
"-family {DejaVu Sans} -size 14 -weight normal -slant roman -underline 0 -overstrike 0"
vTcl:font:add_GUI_font font9 \
"-family {DejaVu Sans Mono} -size 14 -weight normal -slant roman -underline 0 -overstrike 0"
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #b2c9f4
set vTcl(analog_color_p) #eaf4b2
set vTcl(analog_color_m) #f4bcb2
set vTcl(active_fg) #111111
set vTcl(actual_gui_menu_active_bg)  #f4bcb2
set vTcl(active_menu_fg) #000000
}

#############################################################################
# vTcl Code to Load User Fonts

vTcl:font:add_font \
    "-family {DejaVu Sans} -size 12 -weight normal -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font11
vTcl:font:add_font \
    "-family {DejaVu Sans} -size 10 -weight normal -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font12
vTcl:font:add_font \
    "-family {DejaVu Sans Mono} -size 11 -weight normal -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font13
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top39
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top39
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#
    ttk::style configure Menu -background #d9d9d9
    ttk::style configure Menu -foreground #000000
    ttk::style configure Menu -font font9
    menu .pop39 \
        -activebackground {#ffffcd} -activeforeground black \
        -background {#d9d9d9} -font $::vTcl(fonts,vTcl:font12,object) \
        -foreground black -tearoff 1 
    vTcl:DefineAlias ".pop39" "Popupmenu1" vTcl:WidgetProc "" 1
    .pop39 add cascade \
        -menu .pop39.men40 -activebackground {#f4bcb2} \
        -activeforeground {#111111} -background {#d9d9d9} \
        -font [vTcl:font:getFontFromDescr "-family {DejaVu Sans Mono} -size 14 -weight normal -slant roman -underline 0 -overstrike 0"] \
        -foreground {#000000} -label Zoom 
    set site_2_0 "."
    menu .pop39.men40 \
        -activebackground {#ffffcd} -activeforeground black \
        -background {#d9d9d9} -font TkMenuFont -foreground black -tearoff 0 
    .pop39.men40 add command \
        -activebackground {#f4bcb2} -activeforeground {#000000} \
        -background {#d9d9d9} -command lambda:zoom('in') \
        -font [vTcl:font:getFontFromDescr "-family {DejaVu Sans} -size 12 -weight normal -slant roman -underline 0 -overstrike 0"] \
        -foreground {#000000} -label {Zoom In} 
    .pop39.men40 add command \
        -activebackground {#f4bcb2} -activeforeground {#000000} \
        -background {#d9d9d9} -command lambda:zoom('out') \
        -font [vTcl:font:getFontFromDescr "-family {DejaVu Sans} -size 12 -weight normal -slant roman -underline 0 -overstrike 0"] \
        -foreground {#000000} -label {Zoom Out} 
    .pop39.men40 add command \
        -activebackground {#f4bcb2} -activeforeground {#000000} \
        -background {#d9d9d9} -command lambda:zoom('default') \
        -font [vTcl:font:getFontFromDescr "-family {DejaVu Sans} -size 12 -weight normal -slant roman -underline 0 -overstrike 0"] \
        -foreground {#000000} -label {Default Size} 
    .pop39 add command \
        -activebackground {#f4bcb2} -activeforeground {#000000} \
        -background {#d9d9d9} -command refresh \
        -font [vTcl:font:getFontFromDescr "-family {DejaVu Sans} -size 12 -weight normal -slant roman -underline 0 -overstrike 0"] \
        -foreground {#000000} -label Refresh 
    .pop39 add command \
        -activebackground {#f4bcb2} -activeforeground {#000000} \
        -background {#d9d9d9} -command quit \
        -font [vTcl:font:getFontFromDescr "-family {DejaVu Sans} -size 12 -weight normal -slant roman -underline 0 -overstrike 0"] \
        -foreground {#000000} -label Quit 

proc vTclWindow.top39 {base} {
    if {$base == ""} {
        set base .top39
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m40" -background {#d9d9d9} -highlightbackground {#f5deb3} \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1097x789+235+112
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1905 1050
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Two Custom Widgets"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set site_3_0 $top.m40
    menu $site_3_0 \
        -activebackground {#f4bcb2} -activeforeground black \
        -background {#d9d9d9} -font $::vTcl(fonts,vTcl:font11,object) \
        -foreground {#000000} -tearoff 0 
    $site_3_0 add cascade \
        -menu "$site_3_0.men38" -activebackground {#f4bcb2} \
        -activeforeground {#111111} -background {#d9d9d9} \
        -font [vTcl:font:getFontFromDescr "-family {DejaVu Sans} -size 12 -weight normal -slant roman -underline 0 -overstrike 0"] \
        -foreground {#000000} -label Zoom 
    menu $site_3_0.men38 \
        -activebackground {#ffffcd} -activeforeground black \
        -background {#d9d9d9} -font TkMenuFont -foreground black -tearoff 0 
    $site_3_0.men38 add command \
        -activebackground {#f4bcb2} -activeforeground {#000000} \
        -background {#d9d9d9} -command {#lambda:zoom('in')} \
        -font [vTcl:font:getFontFromDescr "-family {DejaVu Sans} -size 12 -weight normal -slant roman -underline 0 -overstrike 0"] \
        -foreground {#000000} -label {Zoom In} 
    $site_3_0.men38 add command \
        -activebackground {#f4bcb2} -activeforeground {#000000} \
        -background {#d9d9d9} -command {#lambda:zoom('out')} \
        -font [vTcl:font:getFontFromDescr "-family {DejaVu Sans} -size 12 -weight normal -slant roman -underline 0 -overstrike 0"] \
        -foreground {#000000} -label {Zoom Out} 
    $site_3_0.men38 add command \
        -activebackground {#f4bcb2} -activeforeground {#000000} \
        -background {#d9d9d9} -command {#lambda:zoom('default')} \
        -font [vTcl:font:getFontFromDescr "-family {DejaVu Sans} -size 12 -weight normal -slant roman -underline 0 -overstrike 0"] \
        -foreground {#000000} -label {Default Size} 
    $site_3_0 add command \
        -activebackground {#f4bcb2} -activeforeground {#000000} \
        -background {#d9d9d9} -command {#refresh} \
        -font [vTcl:font:getFontFromDescr "-family {DejaVu Sans} -size 12 -weight normal -slant roman -underline 0 -overstrike 0"] \
        -foreground {#000000} -label Refresh 
    $site_3_0 add command \
        -activebackground {#f4bcb2} -activeforeground {#000000} \
        -background {#d9d9d9} -command {#quit} \
        -font [vTcl:font:getFontFromDescr "-family {DejaVu Sans} -size 12 -weight normal -slant roman -underline 0 -overstrike 0"] \
        -foreground {#000000} -label Quit 
    frame $top.fra43 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 375 \
        -highlightbackground {#f5deb3} -highlightcolor black -width 265 
    vTcl:DefineAlias "$top.fra43" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra43
    vTcl::widgets::ttk::custom::CreateCmd $site_3_0.cus46 \
        -background {#f5deb3} -height 75 -highlightbackground {#f5deb3} \
        -highlightcolor black -width 125 
    global vTcl
    set val vTcl($site_3_0.cus46,-variant)
    set vTcl($site_3_0.cus46,-variant) _g
    namespace eval ::widgets::$site_3_0.cus46 {}
    set ::widgets::$site_3_0.cus46::ClassOption(-variant) _g
    set ::widgets::$site_3_0.cus46::options(-variant) _g
    set ::widgets::$site_3_0.cus46::save(-variant) 1
    vTcl:DefineAlias "$site_3_0.cus46" "Custom1_4" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.cus46 \
        -in $site_3_0 -x 0 -y 0 -width 0 -relwidth 1 -height 0 -relheight 1 \
        -anchor nw -bordermode ignore 
    button $top.but44 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -command on_btnGetChecks \
        -disabledforeground {#b8a786} -font font9 -foreground {#000000} \
        -highlightbackground {#f5deb3} -highlightcolor black \
        -text {Get Checks} 
    vTcl:DefineAlias "$top.but44" "btnGetChecks" vTcl:WidgetProc "Toplevel1" 1
    button $top.but45 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -command on_btnClearChecks \
        -disabledforeground {#b8a786} -font font9 -foreground {#000000} \
        -highlightbackground {#f5deb3} -highlightcolor black \
        -text {Clear Checks} 
    vTcl:DefineAlias "$top.but45" "btnClearChecks" vTcl:WidgetProc "Toplevel1" 1
    button $top.but48 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -command on_btnExit \
        -disabledforeground {#b8a786} -font font9 -foreground {#000000} \
        -highlightbackground {#f5deb3} -highlightcolor black -text Exit 
    vTcl:DefineAlias "$top.but48" "btnExit" vTcl:WidgetProc "Toplevel1" 1
    message $top.mes49 \
        -background {#d9d9d9} -font $::vTcl(fonts,vTcl:font13,object) \
        -foreground {#000000} -highlightbackground {#f5deb3} \
        -highlightcolor black -relief sunken -text Message -width 421 
    vTcl:DefineAlias "$top.mes49" "Message1" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TSizegrip -background #d9d9d9
    vTcl::widgets::ttk::sizegrip::CreateCmd $top.tSi39 \
        -cursor bottom_right_corner 
    vTcl:DefineAlias "$top.tSi39" "TSizegrip1" vTcl:WidgetProc "Toplevel1" 1
    bind $top.tSi39 <ButtonRelease-1> {
        lambda e: refresh()
    }
    frame $top.fra39 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 495 \
        -highlightbackground {#f5deb3} -highlightcolor black -width 555 
    vTcl:DefineAlias "$top.fra39" "Frame2" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra39
    vTcl::widgets::ttk::custom::CreateCmd $site_3_0.cus40 \
        -background {#f5deb3} -height 75 -highlightbackground {#f5deb3} \
        -highlightcolor black -width 125 
    global vTcl
    set val vTcl($site_3_0.cus40,-variant)
    set vTcl($site_3_0.cus40,-variant) _d
    namespace eval ::widgets::$site_3_0.cus40 {}
    set ::widgets::$site_3_0.cus40::ClassOption(-variant) _d
    set ::widgets::$site_3_0.cus40::options(-variant) _d
    set ::widgets::$site_3_0.cus40::save(-variant) 1
    vTcl:DefineAlias "$site_3_0.cus40" "Custom1" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.cus40 \
        -in $site_3_0 -x 0 -y 0 -width 0 -relwidth 1 -height 0 -relheight 1 \
        -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra43 \
        -in $top -x 80 -y 80 -width 265 -height 375 -anchor nw \
        -bordermode ignore 
    place $top.but44 \
        -in $top -x 130 -y 490 -width 160 -relwidth 0 -height 30 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but45 \
        -in $top -x 130 -y 560 -width 160 -relwidth 0 -height 30 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but48 \
        -in $top -x 160 -y 650 -width 110 -height 30 -anchor nw \
        -bordermode ignore 
    place $top.mes49 \
        -in $top -x 10 -y 10 -width 421 -relwidth 0 -height 63 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tSi39 \
        -in $top -x 0 -relx 1 -y 0 -rely 1 -anchor se -bordermode inside 
    place $top.fra39 \
        -in $top -x 470 -y 83 -width 555 -relwidth 0 -height 504 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top39 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

