#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 7.5e
#  in conjunction with Tcl version 8.6
#    May 28, 2022 07:24:07 PM PDT  platform: Linux

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path

_script = sys.argv[0]
_location = os.path.dirname(_script)

import menu_support

_bgcolor = 'wheat'  # X11 color: #f5deb3
_fgcolor = '#000000'  # X11 color: 'black'
_compcolor = '#b2c9f4' # Closest X11 color: 'SlateGray2'
_ana1color = '#eaf4b2' # Closest X11 color: '{pale goldenrod}'
_ana2color = '#f4bcb2' # Closest X11 color: 'RosyBrown2'
_tabfg1 = 'black' 
_tabfg2 = 'black' 
_tabbg1 = 'grey75' 
_tabbg2 = 'grey89' 
_bgmode = 'light' 
font15 = "-family {DejaVu Sans} -size 12"

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("644x420+664+535")
        top.minsize(1, 1)
        top.maxsize(1905, 1170)
        top.resizable(1,  1)
        top.title("Menu Example")
        top.configure(background="wheat")
        top.configure(highlightbackground="wheat")
        top.configure(highlightcolor="black")

        self.top = top
        self.IRS = tk.StringVar()
        self.Charity = tk.StringVar()
        self.selectedButton = tk.StringVar()
        self.Check_1 = tk.StringVar()
        self.Check_2 = tk.StringVar()

        self.menubar = tk.Menu(top, font="-family {DejaVu Sans} -size 12"
                ,bg='#ff0000', fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.sub_menu = tk.Menu(top,
                activebackground="#f9f9f9",
                activeforeground="black",
                background="#ffff00",
                disabledforeground="#b8a786",
                foreground="black",
                tearoff=0)
        self.menubar.add_cascade(menu=self.sub_menu,
                background="#00ffff",
                compound="left",
                font="-family {Purisa} -size 12",
                foreground="#000000",
                label="File")
        self.sub_menu.add_command(
                command=menu_support.save,
                foreground="#000000",
                label="Save")
        self.sub_menu.add_separator(
)
        photo_location = os.path.join(_location,"./stop.gif")
        global _img0
        _img0 = tk.PhotoImage(file=photo_location)
        self.sub_menu.add_command(
                command=menu_support.quit,
                compound="top",
                image=_img0,
                label="Quit")
        self.sub_menu1 = tk.Menu(top,
                activebackground="#f9f9f9",
                activeforeground="black",
                background="#ff0000",
                disabledforeground="#b8a786",
                foreground="white",
                tearoff=0)
        self.menubar.add_cascade(menu=self.sub_menu1,
                background="#990000",
                compound="left",
                font="-family {Purisa} -size 12",
                foreground="#ffff00",
                label="Edit")
        self.sub_menu1.add_command(
                command=menu_support.cut,
                label="Cut")
        self.sub_menu1.add_command(
                command=menu_support.copy,
                label="Copy")
        self.sub_menu1.add_separator(
)
        self.sub_menu1.add_command(
                command=menu_support.paste,
                label="Paste")
        self.sub_menu12 = tk.Menu(top,
                activebackground="#f9f9f9",
                activeforeground="black",
                background="#ffff00",
                disabledforeground="#b8a786",
                foreground="black",
                tearoff=0)
        self.sub_menu1.add_cascade(menu=self.sub_menu12,
                label="Other")
        self.sub_menu12.add_command(
                command=menu_support.post,
                label="Post")
        self.sub_menu12.add_command(
                command=menu_support.sync,
                label="Sync")
        self.sub_menu123 = tk.Menu(top,
                activebackground="#f9f9f9",
                activeforeground="black",
                background="plum",
                disabledforeground="#b8a786",
                foreground="black",
                tearoff=0)
        self.sub_menu12.add_cascade(menu=self.sub_menu123,
                label="Still")
        self.sub_menu123.add_command(
                command=menu_support.yes,
                label="Yes")
        self.sub_menu123.add_command(
                command=menu_support.no,
                label="No")
        self.sub_menu123.add_checkbutton(
                variable=self.IRS,
                label="IRS")
        self.sub_menu123.add_checkbutton(
                variable=self.Charity,
                background="plum",
                label="Charity")
        self.sub_menu1234 = tk.Menu(top,
                activebackground="#f9f9f9",
                activeforeground="black",
                background="#ff0000",
                disabledforeground="#b8a786",
                foreground="black",
                tearoff=0)
        self.sub_menu123.add_cascade(menu=self.sub_menu1234,
                label="More")
        self.sub_menu1234.add_radiobutton(
                value='1',
                variable=self.selectedButton,
                activebackground="#d9d9d9",
                activeforeground="#000000",
                background="#ffff00",
                command=menu_support.radio_a,
                font="TkMenuFont",
                foreground="#000000",
                label="Radio-A")
        self.sub_menu1234.add_radiobutton(
                value='2',
                variable=self.selectedButton,
                activebackground="#d9d9d9",
                activeforeground="#000000",
                background="#00ff00",
                command=menu_support.radio_b,
                font="TkMenuFont",
                foreground="#000000",
                label="Radio-B")
        photo_location = os.path.join(_location,"./openfold.gif")
        global _img1
        _img1 = tk.PhotoImage(file=photo_location)
        self.sub_menu1234.add_checkbutton(
                selectcolor="#990000",
                variable=self.Check_1,
                activebackground="#d9d9d9",
                activeforeground="#000000",
                background="#ff0000",
                command=menu_support.check1,
                compound="left",
                font="TkMenuFont",
                foreground="#000000",
                image=_img1,
                label="Check 1")
        self.sub_menu1234.add_checkbutton(
                variable=self.Check_2,
                activebackground="#d9d9d9",
                activeforeground="#000000",
                background="#ff0000",
                command=menu_support.check2,
                foreground="#000000",
                label="Check 2")

def start_up():
    menu_support.main()

if __name__ == '__main__':
    menu_support.main()




