#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 7g
#  in conjunction with Tcl version 8.6
#    Jun 13, 2021 06:34:57 AM PDT  platform: Linux

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import popup

def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol( 'WM_DELETE_WINDOW' , root.destroy)
    # Creates a toplevel widget.
    global _top36, _w36
    _top36 = root
    _w36 = popup.Toplevel1(_top36)
    root.mainloop()

def how(*args):
    print('popup_support.how')
    sys.stdout.flush()

def moo(*args):
    print('popup_support.moo')
    sys.stdout.flush()

def now(*args):
    print('popup_support.now')
    sys.stdout.flush()

def quit(*args):
    print('popup_support.quit')
    sys.stdout.flush()
    sys.exit()

def that(*args):
    print('popup_support.that')
    sys.stdout.flush()

def then(*args):
    print('popup_support.then')
    sys.stdout.flush()

def there(*args):
    print('popup_support.there')
    sys.stdout.flush()

def this(*args):
    print('popup_support.this')
    sys.stdout.flush()

if __name__ == '__main__':
    popup.start_up()




