#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 6.1g
#  in conjunction with Tcl version 8.6
#    Mar 07, 2021 05:11:53 PM PST  platform: Linux

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import time
import progress_bar
import globals

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def advance():
    global bar, bar_value
    import progress_bar_support
    if not progress_bar.w:
        print("creating progress bar")
        # If the progress bar has not been previously created,
        # create it; note the parameter 'root'.
        bar = progress_bar.create_Progress_Bar(root)
        # The above gives us access to functions and attributes of
        # the progress_bar object.
        bar_value = globals.prog_var.get() / float(100)
        print ("Value to display: %f" % bar_value)
        return
    if bar_value < 1.0:
        bar_value += 0.2
        print ("Value to display: %f" % bar_value)
        globals.prog_var.set(int(bar_value*100))
        root.update() # This updates Tk for both this and the progress_bar.
    if bar_value >= 1.0:
        time.sleep(1)        # Wait one second and then kill the progress bar
        #globals.destroy_window()
        progress_bar_support.destroy_window()
        progress_bar.w = None
        bar_value = 0.0


def quit():
    print('new_support.quit')
    sys.stdout.flush()
    sys.exit()

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import new
    new.vp_start_gui()




