language: python

python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"

addons:
  apt:
    packages:
      - "xvfb"

branches:
  only:
    - master
    - develop

install:
  - pip install appdirs

before_script:
  - "export DISPLAY=:99.0"
  - "Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &"
  - sleep 3 # give xvfb some time to start

script:
  - cd tests
  - python -m unittest discover
